export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const ADD_USER = "ADD_USER";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const UPDATE_USER = "UPDATE_USER";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const ADD_COURSE = "ADD_COURSE";
export const GET_COURSE_LIST = "GET_COURSE_LIST";
export const GET_COURSE_LIST_SUCCESS = "GET_COURSE_LIST_SUCCESS";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";

export const GET_DETAILS = "GET_DETAILS";
export const GET_DETAILS_SUCCESS = "GET_DETAILS_SUCCESS";
export const ADD_DETAILS_COURSE = "ADD_DETAILS_COURSE";
export const UPDATE_USER_CART = "UPDATE_USER_CART";

export const ADD_QUESTION = "ADD_QUESTION";
export const GET_ALL_QUESTIONS = "GET_ALL_QUESTIONS";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const ANSWER_QUESTION = "ANSWER_QUESTION";