export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const ADD_USER = "ADD_USER";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"; 
export const UPDATE_USER = "UPDATE_USER";

export const ADD_CATEGORY="ADD_CATEGORY"; 
export const GET_CATEGORY="GET_CATEGORY"; 
export const GET_CATEGORY_SUCCESS="GET_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY="UPDATE_CATEGORY";
export const DELETE_CATEGORY="DELETE_CATEGORY";